### ISSUE TITLE
Cannot find module node_sqlite3.node

### ISSUE THREAD

**Issue by vitolipari** [leota/electron-angular4-sqlite3#4]
When i type on terminal `npm run electron` i have this error:
```
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/Users/vitolipari/job/LipariStudios/app/ElectronAngular4SQLite3_Sample/node_modules/sqlite3/lib/binding/electron-v1.7-darwin-x64/node_sqlite3.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/vitolipari/job/LipariStudios/app/ElectronAngular4SQLite3_Sample/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vitolipari/job/LipariStudios/app/ElectronAngular4SQLite3_Sample/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/Users/vitolipari/job/LipariStudios/app/ElectronAngular4SQLite3_Sample/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Client_SQLite3._driver (/Users/vitolipari/job/LipariStudios/app/ElectronAngular4SQLite3_Sample/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/Users/vitolipari/job/LipariStudios/app/ElectronAngular4SQLite3_Sample/node_modules/knex/lib/client.js:219:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-electron-sqlite@0.0.0 electron: `npm run build-electron && electron dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-electron-sqlite@0.0.0 electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vitolipari/.npm/_logs/2017-12-08T13_44_45_983Z-debug.log
```

**Comment by leota** [comment]
Did you run `npm install` to install all needed packages?

**Comment by vitolipari** [comment]
yes.
I solved!
_Thank you for answer_!
